### ISSUE TITLE
NoSQL comparison PouchDB vs CouchDB vs Couchbase

### ISSUE THREAD

**Issue by ClydeShen** [iuv-dev/routeapp#12]
In terms of front-end Database, thanks for @raira-mioma suggestions, we need compare some of them to make decision for NoSQL
- [x] Do research about PouchDB
- [x] Do research about CouchDB
- [x] Do research about Couchbase
- [x] compare them think about
  - support AngularJS and Cordova
  - support most browsers, as many as possible
  - easy to implementation
  - easy to query and see result
- [x] is there any specific plugin or tools for it.

**Comment by raira-mioma** [comment]
Alright, let's do this!

First of all, I guess, CouchDB is more suitable for applications of larger scope:

>  CouchDB is one of the leading open source document store databases. PouchDB is, as the name suggests, an in-browser counterpart to CouchDB. ([From here](https://blog.engineyard.com/2014/an-introduction-to-pouchdb))

_Probably, we may use CouchDB on our server in future. _

> PouchDB is a database that lives inside your browser. The primary advantage of this is that you don’t have to perform queries over the network. This makes queries faster, since they’re not susceptible to the vagaries of network weather, and more reliable, since even if the user is offline they can use whatever information has been locally cached. In some cases, what has been locally cached may even be primary data. In this case PouchDB can store it for you, and will wait until the network connection comes back before syncing it to a remote server if asked to do so.

That's exactly what we need, isn't it?

Couchbase Mobile is designed for the same scope of projects: http://developer.couchbase.com/mobile/

Now the question is:*\* Couchbase LIte or PouchDB?**

I've been searching today about Couchbase Lite and PouchDB. Both of them are mentioned a lot and recommended for use in hybrid(web & mobile) apps which require storage on device.

[Performance comparison](http://www.mircozeiss.com/pouchdb-vs-couchbase-lite-a-performance-review)  shows us that PouchDB is better.

Both couchbase-lite and pouchdb work with AngularJS.

As for browser support: PouchDB uses both WebSQL and IndexedDB technologies both, so it has excellent [browser support](https://pouchdb.com/adapters.html). 

Surprisingly, I haven't found anything about browser support of Couchbase Lite(!!!)

That's all for today, but the issue is not closed. I should see how easy is it to implement and try to make a query. Probably, on Sunday.
